model: tem

mitomodel: code/dj/my_original/checkpoint/tem_mito.h5
ermodel: code/dj/my_original/checkpoint/tem_er.pth

# 要处理的数据集JSON文件保存位置
datadir: data/tissues/json/test/20210111_3Label_ER-Mito-LD
#datadir: data/cell/json/test/202011_HBSSControl

outputdir: ./results

resolution: 10.0

threshold: 0.3
px: 10

repeat_num: 5